import type { Metadata } from "next";
import "./globals.css";
import "./font.css"

import { HeroUI } from "@/components/HeroUi";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it">
      <body>
        <HeroUI>
          <Header />
          <main className="pt-20">{children}</main>
          <Footer />
        </HeroUI>
      </body>
    </html>
  );
}
